# This file was *autogenerated* from the file p10.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2000000 = Integer(2000000)
s = _sage_const_0 
x = _sage_const_1 
while next_prime(x) < _sage_const_2000000 :
    x = next_prime(x)
    s += x
print s
