# This file was *autogenerated* from the file p12.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_500 = Integer(500)
i = _sage_const_1 
x = _sage_const_1 
while True:
    n = len(divisors(x))
    if n > _sage_const_500 :
        break
    i += _sage_const_1 
    x = i * (i + _sage_const_1 ) / _sage_const_2 

print x
