# This file was *autogenerated* from the file p21.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10000 = Integer(10000)
def sum_proper_divisors(x):
    return sum(divisors(x)[:-_sage_const_1 ])

num = [_sage_const_0 ] * _sage_const_10000 
for i in range(_sage_const_2 , _sage_const_10000 ):
    num[i] = sum_proper_divisors(i)

amicable_numbers = set()
for i in range(_sage_const_2 , _sage_const_10000 ):
    if num[i] < _sage_const_10000  and i != num[i] and num[num[i]] == i: 
        amicable_numbers.add(i)

print amicable_numbers
print sum(amicable_numbers)
