# This file was *autogenerated* from the file p23.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_28123 = Integer(28123)
def is_abundant(x):
    return sum(divisors(x)[:-_sage_const_1 ]) > x

abundant_nums = set()
for i in range(_sage_const_1 , _sage_const_28123  + _sage_const_1 ):
    if is_abundant(i):
        abundant_nums.add(i)

nums_written = set()
for x in abundant_nums:
    for y in abundant_nums:
        nums_written.add(x + y)

sum = _sage_const_0 
for i in range(_sage_const_1 , _sage_const_28123  + _sage_const_1 ):
    if i not in nums_written:
        sum += i
print sum
