# This file was *autogenerated* from the file p27.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_999 = Integer(999); _sage_const_1000 = Integer(1000)
def get_len(a, b):
    f = lambda x: x**_sage_const_2  + a*x + b
    i = _sage_const_0 
    while True:
        if f(i) not in Primes():
            break
        else:
            i += _sage_const_1 
    return i

max_len = _sage_const_0 
max_a = None
max_b = None
for a in range(-_sage_const_999 , _sage_const_1000 ):
    print a,
    for b in range(_sage_const_2 , _sage_const_1000 ):
        if b not in Primes():
            continue
        this_len = get_len(a, b)
        if max_len < this_len:
            max_len = this_len
            max_a = a
            max_b = b
print
print max_a * max_b

        

