# This file was *autogenerated* from the file p3.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_600851475143 = Integer(600851475143); _sage_const_0 = Integer(0)#!/usr/bin/env sage

a = _sage_const_600851475143 
r = factor(a)
s = _sage_const_0 
for x, d in list(r):
    s += x
print x

