# This file was *autogenerated* from the file p37.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_11 = Integer(11)
def is_good(x):
    s = list(str(x))
    l = len(s)
    n = ''
    for i in range(l - _sage_const_1 ):
        n += s[i]
        if int(n) not in Primes():
            return False
    n = ''
    for i in range(l - _sage_const_1 ):
        n = s[l - i - _sage_const_1 ] + n
        if int(n) not in Primes():
            return False
    return True

p = _sage_const_11 
results = set()
while True:
    p = next_prime(p)
    if is_good(p):
        results.add(p)
        print results
        if len(results) == _sage_const_11 :
            break
print results
print sum(results)
