# This file was *autogenerated* from the file p41.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9)
def is_pandigital(x):
    st = str(x)
    ss = frozenset(st)
    for i in range(_sage_const_1 , len(st) + _sage_const_1 ):
        if str(i) not in ss:
            return False
    return True

#print is_pandigital(2143)

from itertools import permutations
for length in range(_sage_const_9 , _sage_const_0 , -_sage_const_1 ):
    gen_str = reduce(lambda a, b: a + b, [str(i) for i in range(length, _sage_const_0 , -_sage_const_1 )])
    print gen_str
    gen = permutations(gen_str, length)
    for t in gen:
        x = int(''.join(t))
        if x in Primes():
            print 'Found', x
            import sys
            sys.exit()
