# This file was *autogenerated* from the file p46.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_9 = Integer(9); _sage_const_1 = Integer(1)
from math import sqrt

x = _sage_const_9 
while True:
    x += _sage_const_2 
    if x in Primes():
        continue

    passed = False
    for i in range(_sage_const_1 , int(sqrt(x / _sage_const_2 )) + _sage_const_1 ):
        if x - _sage_const_2  * (i ** _sage_const_2 ) in Primes():
            passed = True
            break
    if not passed:
        break
print x
