# This file was *autogenerated* from the file p47.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4)
def get_factors(x):
    return frozenset([a for a, b in factor(x)])

i = _sage_const_4 
while True:
    #if i % 1000 == 0:
        #print i

    set_1 = get_factors(i)
    if len(set_1) != _sage_const_4 :
        i += _sage_const_1 
        continue

    set_2 = get_factors(i + _sage_const_1 )
    if len(set_2) != _sage_const_4 :
        i += _sage_const_2 
        continue
    if len(set_1 & set_2) != _sage_const_0 :
        i += _sage_const_1 
        continue

    set_3 = get_factors(i + _sage_const_2 )
    if len(set_3) != _sage_const_4 :
        i += _sage_const_3 
        continue
    if len(set_2 & set_3) != _sage_const_0 :
        i += _sage_const_2 
        continue

    set_4 = get_factors(i + _sage_const_3 )
    if len(set_4) != _sage_const_4 :
        i += _sage_const_4 
        continue
    if len(set_3 & set_4) != _sage_const_0 :
        i += _sage_const_3 
        continue

    break

print i
