# This file was *autogenerated* from the file p50.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1000000 = Integer(1000000); _sage_const_1000 = Integer(1000)
start = _sage_const_2 
results = {}
while start < _sage_const_1000 :
    i = start

    num = _sage_const_0 
    prime_num = None

    total = _sage_const_0 
    prime_total = None

    added = set()
    prime_added = None

    while total + i < _sage_const_1000000 :
        num += _sage_const_1 
        added.add(i)
        total += i
        if total in Primes():
            prime_total = total
            prime_added = added
            prime_num = num
        i = next_prime(i)
    results[prime_num] = prime_total  # , prime_added)

    start = next_prime(start)

#print results
print max(results), results[max(results)]
