# This file was *autogenerated* from the file p51.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_100000 = Integer(100000)#!/usr/bin/env sage


def num_primes(str_x, debug=False):
    num = _sage_const_0 

    if str_x[_sage_const_0 ] == '*':
        gen = range(_sage_const_1 , _sage_const_10 )
    else:
        gen = range(_sage_const_10 )

    for i in gen:
        c = str(i)
        x = str_x.replace('*', c)
        if int(x) in Primes():
            if debug:
                print x
            num += _sage_const_1 

    return num

from itertools import combinations

x = _sage_const_100000 
while True:
    x = next_prime(x)
    for i in range(_sage_const_1 , len(str(x))):
        pos_gen = combinations(range(len(str(x))), i)
        for pos in pos_gen:
            lis_x = list(str(x))
            for j in pos:
                lis_x[j] = '*'
            str_x = ''.join(lis_x)
            if num_primes(str_x) == _sage_const_8 :
                print x, str_x
                print num_primes(str_x, debug=True)
                import sys
                sys.exit()
