# This file was *autogenerated* from the file p7.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_10001 = Integer(10001)
p = _sage_const_1 
for i in range(_sage_const_10001 ):
    p = next_prime(p)
print p
